---
- name: Cloudlab basic provision
  hosts: cloudlab-controller
  become: yes
  vars:
    ansible_user: ubuntu

  tasks:
   - name: Add user "{{username}}"
     user:
       name: "{{username}}"
       password: "*"
       group: sudo
       state: present

  vars_prompt:
   - name: "username"
     prompt: "what is your name?"
