---
tacacs_servers:
<<<<<<< HEAD
 - 192.168.0.10
 - 192.168.0.11
tacacs_port: 53
tacacs_secret: default
=======
 - 10.10.10.10
 - 10.10.10.20
tacacs_port: 49
tacacs_secret: secret
packages:
  - libpam-tacplus 
permissions_other_read:
  - /etc/pam.d/
  - /usr/share/pam-configs/tacplus

>>>>>>> c569c5a4579a8a5dcf44fbe484546303e240dedc

