- name: install java
  hosts: all
  become: true
  tasks:
    - name: Add Oracle Java PPA to apt sources list
      apt_repository: repo='ppa:webupd8team/java' state=present
    - name: Accept Java 8 License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    - name: Ensure Java is installed.
      apt: name=oracle-java8-installer state=present install_recommends=yes update_cache=yes

